export default function Blank() {
  return (<>
      <div className="w-1/12"></div>
    <div className="w-1 h-8 bg-purple-600"></div>
    <div className="w-2 bg-red-600"></div>
    <div className="w-3 bg-yellow-600"></div>
    <div className="w-4 bg-orange-600"></div>
    <div className="w-5 bg-amber-600"></div>
    <div className="w-6 bg-lime-600"></div>
    <div className="bg-teal-600 w-7"></div>
    <div className="w-8 bg-blue-600"></div>
    <div className="bg-pink-600 w-9"></div>
    <div className="w-10 bg-rose-600"></div>
    <div className="w-11 bg-cyan-600"></div>
    <div className="w-12 bg-black"></div>
    <div className="bg-orange-100 w-13"></div>
    <div className="w-14"></div>
    <div className="w-15"></div>
    <div className="w-16"></div>
    <div className="w-17"></div>
    <div className="w-18"></div>
    <div className="w-19"></div>
    <div className="w-20"></div>
    <div className="w-21"></div>
    <div className="w-22"></div>
    <div className="w-23"></div>
    <div className="w-24"></div>
    <div className="w-25"></div>
    <div className="w-26"></div>
    <div className="w-27"></div>
    <div className="w-28"></div>
    <div className="w-29"></div>
    <div className="w-30"></div>
    <div className="w-31"></div>
    <div className="w-32"></div>
    <div className="w-33"></div>
    <div className="w-34"></div>
    <div className="w-35"></div>
    <div className="w-36"></div>
    <div className="w-37"></div>
    <div className="w-38"></div>
    <div className="w-39"></div>
    <div className="w-40"></div>
    <div className="w-41"></div>
    <div className="w-42"></div>
    <div className="w-43"></div>

    <div className="w-1/48"></div>
    <div className="w-2/48"></div>
    <div className="w-3/48"></div>
    <div className="w-4/48 "></div>
    <div className="w-5/48 "></div>
    <div className="w-6/48 "></div>
    <div className="w-7/48"></div>
    <div className="w-8/48 "></div>
    <div className="w-9/48"></div>
    <div className="w-10/48 "></div>
    <div className="w-11/48 "></div>
    <div className="w-12/48 "></div>
    <div className="w-13/48"></div>
    <div className="w-14/48"></div>
    <div className="w-15/48"></div>
    <div className="w-16/48"></div>
    <div className="w-17/48"></div>
    <div className="w-18/48"></div>
    <div className="w-19/48"></div>
    <div className="w-20/48"></div>
    <div className="w-21/48"></div>
    <div className="w-22/48"></div>
    <div className="w-23/48"></div>
    <div className="w-24/48"></div>
    <div className="w-25/48"></div>
    <div className="w-26/48"></div>
    <div className="w-27/48"></div>
    <div className="w-28/48"></div>
    <div className="w-29/48"></div>
    <div className="w-30/48"></div>
    <div className="w-31/48"></div>
    <div className="w-32/48"></div>
    <div className="w-33/48"></div>
    <div className="w-34/48"></div>
    <div className="w-35/48"></div>
    <div className="w-36/48"></div>
    <div className="w-37/48"></div>
    <div className="w-38/48"></div>
    <div className="w-39/48"></div>
    <div className="w-40/48"></div>
    <div className="w-41/48"></div>
    <div className="w-42/48"></div>
    <div className="w-43/48"></div>
    <div className="w-44/48"></div>
    <div className="w-45/48"></div>
    <div className="w-46/48"></div>
    <div className="w-47/48"></div>
    <div className="w-48/48"></div>

    <div className="col-span-1"></div>
    <div className="col-span-2"></div>
    <div className="col-span-3"></div>
    <div className="col-span-4 "></div>
    <div className="col-span-5 "></div>
    <div className="col-span-6 "></div>
    <div className="col-span-7"></div>
    <div className="col-span-8 "></div>
    <div className="col-span-9"></div>
    <div className="col-span-10"></div>
    <div className="col-span-11"></div>
    <div className="col-span-12"></div>
    <div className="col-span-13"></div>
    <div className="col-span-14"></div>
    <div className="col-span-15"></div>
    <div className="col-span-16"></div>
    <div className="col-span-17"></div>
    <div className="col-span-18"></div>
    <div className="col-span-19"></div>
    <div className="col-span-20"></div>
    <div className="col-span-21"></div>
    <div className="col-span-22"></div>
    <div className="col-span-23"></div>
    <div className="col-span-24"></div>
    <div className="col-span-25"></div>
    <div className="col-span-26"></div>
    <div className="col-span-27"></div>
    <div className="col-span-28"></div>
    <div className="col-span-29"></div>
    <div className="col-span-30"></div>
    <div className="col-span-31"></div>
    <div className="col-span-32"></div>
    <div className="col-span-33"></div>
    <div className="col-span-34"></div>
    <div className="col-span-35"></div>
    <div className="col-span-36"></div>
    <div className="col-span-37"></div>
    <div className="col-span-38"></div>
    <div className="col-span-39"></div>
    <div className="col-span-40"></div>
    <div className="col-span-41"></div>
    <div className="col-span-42"></div>
    <div className="col-span-43"></div>
    <div className="col-span-44"></div>
    <div className="col-span-45"></div>
    <div className="col-span-46"></div>
    <div className="col-span-47"></div>
    <div className="col-span-48"></div>
    <div className="col-span-49"></div>
    <div className="col-span-50"></div>
    <div className="col-span-51"></div>
    <div className="col-span-52"></div>
    <div className="col-span-53"></div>
    <div className="col-span-54 "></div>
    <div className="col-span-55 "></div>
    <div className="col-span-56 "></div>
    <div className="col-span-57"></div>
    <div className="col-span-58 "></div>
    <div className="col-span-59"></div>
    <div className="col-span-60"></div>
    <div className="col-span-61"></div>
    <div className="col-span-62"></div>
    <div className="col-span-63"></div>
    <div className="col-span-64"></div>
    <div className="col-span-65"></div>
    <div className="col-span-66"></div>
    <div className="col-span-67"></div>
    <div className="col-span-68"></div>
    <div className="col-span-69"></div>
    <div className="col-span-70"></div>
    <div className="col-span-71"></div>
    <div className="col-span-72"></div>
    <div className="col-span-73"></div>
    <div className="col-span-74"></div>
    <div className="col-span-75"></div>
    <div className="col-span-76"></div>
    <div className="col-span-77"></div>
    <div className="col-span-78"></div>
    <div className="col-span-79"></div>
    <div className="col-span-80"></div>
    <div className="col-span-81"></div>
    <div className="col-span-82"></div>
    <div className="col-span-83"></div>
    <div className="col-span-84"></div>
    <div className="col-span-85"></div>
    <div className="col-span-86"></div>
    <div className="col-span-87"></div>
    <div className="col-span-88"></div>
    <div className="col-span-89"></div>
    <div className="col-span-90"></div>
    <div className="col-span-91"></div>
    <div className="col-span-92"></div>
    <div className="col-span-93"></div>
    <div className="col-span-94"></div>
    <div className="col-span-95"></div>
    <div className="col-span-96"></div>

    <div className="w-0.5ch"></div>
    <div className="w-1.5ch"></div>
    <div className="w-2.5ch"></div>
    <div className="w-3.5ch"></div>
    <div className="w-4.5ch"></div>
    <div className="w-5.5ch"></div>
    <div className="w-6.5ch"></div>
    <div className="w-7.5ch"></div>
    <div className="w-8.5ch"></div>
    <div className="w-9.5ch"></div>
    <div className="w-10.5ch"></div>
    <div className="w-11.5ch"></div>
    <div className="w-12.5ch"></div>
    <div className="w-13.5ch"></div>
    <div className="w-14.5ch"></div>
    <div className="w-15.5ch"></div>
    <div className="w-16.5ch"></div>
    <div className="w-17.5ch"></div>
    <div className="w-18.5ch"></div>
    <div className="w-19.5ch"></div>
    <div className="w-20.5ch"></div>
    <div className="w-21.5ch"></div>
    <div className="w-22.5ch"></div>
    <div className="w-23.5ch"></div>
    <div className="w-24.5ch"></div>
    <div className="w-25.5ch"></div>
    <div className="w-26.5ch"></div>
    <div className="w-27.5ch"></div>
    <div className="w-28.5ch"></div>
    <div className="w-29.5ch"></div>
    <div className="w-30.5ch"></div>
    <div className="w-31.5ch"></div>
    <div className="w-32.5ch"></div>
    <div className="w-33.5ch"></div>
    <div className="w-34.5ch"></div>
    <div className="w-35.5ch"></div>
    <div className="w-36.5ch"></div>
    <div className="w-37.5ch"></div>
    <div className="w-38.5ch"></div>
    <div className="w-39.5ch"></div>
    <div className="w-40.5ch"></div>
    <div className="w-41.5ch"></div>
    <div className="w-42.5ch"></div>
    <div className="w-43.5ch"></div>
    <div className="w-44.5ch"></div>
    <div className="w-45.5ch"></div>
    <div className="w-46.5ch"></div>
    <div className="w-47.5ch"></div>
    <div className="w-48.5ch"></div>
    <div className="w-49.5ch"></div>
    <div className="w-50.5ch"></div>
    <div className="w-51.5ch"></div>
    <div className="w-52.5ch"></div>
    <div className="w-53.5ch"></div>
    <div className="w-54.5ch"></div>
    <div className="w-55.5ch"></div>
    <div className="w-56.5ch"></div>
    <div className="w-57.5ch"></div>
    <div className="w-58.5ch"></div>
    <div className="w-59.5ch"></div>
    <div className="w-60.5ch"></div>
    <div className="w-61.5ch"></div>
    <div className="w-62.5ch"></div>
    <div className="w-63.5ch"></div>
    <div className="w-64.5ch"></div>
    <div className="w-65.5ch"></div>
    <div className="w-66.5ch"></div>
    <div className="w-67.5ch"></div>
    <div className="w-68.5ch"></div>
    <div className="w-69.5ch"></div>
    <div className="w-70.5ch"></div>
    <div className="w-71.5ch"></div>
    <div className="w-72.5ch"></div>

    <div className="w-1ch"></div>
    <div className="w-2ch"></div>
    <div className="w-3ch"></div>
    <div className="w-4ch"></div>
    <div className="w-5ch"></div>
    <div className="w-6ch"></div>
    <div className="w-7ch"></div>
    <div className="w-8ch"></div>
    <div className="w-9ch"></div>
    <div className="w-10ch"></div>
    <div className="w-11ch"></div>
    <div className="w-12ch"></div>
    <div className="w-13ch"></div>
    <div className="w-14ch"></div>
    <div className="w-15ch"></div>
    <div className="w-16ch"></div>
    <div className="w-17ch"></div>
    <div className="w-18ch"></div>
    <div className="w-19ch"></div>
    <div className="w-20ch"></div>
    <div className="w-21ch"></div>
    <div className="w-22ch"></div>
    <div className="w-23ch"></div>
    <div className="w-24ch"></div>
    <div className="w-25ch"></div>
    <div className="w-26ch"></div>
    <div className="w-27ch"></div>
    <div className="w-28ch"></div>
    <div className="w-29ch"></div>
    <div className="w-30ch"></div>
    <div className="w-31ch"></div>
    <div className="w-32ch"></div>
    <div className="w-33ch"></div>
    <div className="w-34ch"></div>
    <div className="w-35ch"></div>
    <div className="w-36ch"></div>
    <div className="w-37ch"></div>
    <div className="w-38ch"></div>
    <div className="w-39ch"></div>
    <div className="w-40ch"></div>
    <div className="w-41ch"></div>
    <div className="w-42ch"></div>
    <div className="w-43ch"></div>
    <div className="w-44ch"></div>
    <div className="w-45ch"></div>
    <div className="w-46ch"></div>
    <div className="w-47ch"></div>
    <div className="w-48ch"></div>
    <div className="w-49ch"></div>
    <div className="w-50ch"></div>
    <div className="w-51ch"></div>
    <div className="w-52ch"></div>
    <div className="w-53ch"></div>
    <div className="w-54ch"></div>
    <div className="w-55ch"></div>
    <div className="w-56ch"></div>
    <div className="w-57ch"></div>
    <div className="w-58ch"></div>
    <div className="w-59ch"></div>
    <div className="w-60ch"></div>
    <div className="w-61ch"></div>
    <div className="w-62ch"></div>
    <div className="w-63ch"></div>
    <div className="w-64ch"></div>
    <div className="w-65ch"></div>
    <div className="w-66ch"></div>
    <div className="w-67ch"></div>
    <div className="w-68ch"></div>
    <div className="w-69ch"></div>
    <div className="w-70ch"></div>
    <div className="w-71ch"></div>
    <div className="w-72ch"></div>
    </>
  )
}