import { FC, useEffect, useState } from 'react'
import API from '@aws-amplify/api'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CreateAccount from '../components/createAccount'

interface IndexProps {
  startTrackingFn: Function
}

const Index = (props: IndexProps) => {
  
  return (
    <main className={styles.main}>
      <h1 className={styles.title}>
        <button
          className="text-blue-600"
          onClick={() => props.startTrackingFn('create')}
        >Start tracking
        </button>
      </h1>
      <div>
      </div>
    </main>
  )
}

const Home: NextPage = () => {

  const [state, setState] = useState({
    page: '',
    auth: false
  })

  const startTrackingFn = (e: string) => {
    setState({...state, [state.page]: e})
  }



  useEffect(() => {
    (async () => {
      try {
        const data = await API.get(process.env.NEXT_PUBLIC_APIGATEWAY_NAME??"", '/getUserMonth', {})
        console.log('data', data)
      } catch (err) {
        console.log('err', err)
      }
    })()
  }, [])

  
  return (
    <div className={styles.container}>
      <Head>
        <script src="https://apis.google.com/js/platform.js" async defer></script>
        <title>Timebar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { state.page === '' && <Index startTrackingFn={startTrackingFn}/>}
      { state.page === 'create' && <CreateAccount changeState={() => setState({...state, page: 'create'})}/>}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home